In [17]:
import numpy as np

In [18]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
print(np.linspace(3,4,10))

[3.         3.11111111 3.22222222 3.33333333 3.44444444 3.55555556
 3.66666667 3.77777778 3.88888889 4.        ]


In [21]:
print(np.zeros((3,4),dtype = int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [22]:
print(np.random.random((2,2)))

[[0.76824586 0.2895438 ]
 [0.09041187 0.34020575]]


In [27]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.83786854e-321],
       [1.13102376e-311, 1.13102376e-311, 1.13214079e-311]])

In [30]:
print(np.full((3,3),9))

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [138]:
print(np.arange(10,50,5))

[10 15 20 25 30 35 40 45]


In [139]:
print(np.linspace(10,50,5,dtype=int))

[10 20 30 40 50]


In [75]:
j = np.array([[1,2],[3,4],[5,6]])
print(j.ndim)
print(j.shape)

2
(3, 2)


In [93]:
print(j.size)

6


In [94]:
print(j.itemsize)

4


In [96]:
print(j.nbytes)  # nbytes = size * itemsize

24


In [97]:
print(len(a))

3


In [140]:
x = np.ones((3,4),int)
print(x)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [100]:
print(x.shape)

(3, 4)


In [101]:
 y = np.random.random((3,4))
print(y)

[[0.09050262 0.19955983 0.73074003 0.69509934]
 [0.48299066 0.36192311 0.68094966 0.62377596]
 [0.39366758 0.86361704 0.06486544 0.73315885]]


In [102]:
print(y.shape)

(3, 4)


In [103]:
z = x + y
z

array([[1.09050262, 1.19955983, 1.73074003, 1.69509934],
       [1.48299066, 1.36192311, 1.68094966, 1.62377596],
       [1.39366758, 1.86361704, 1.06486544, 1.73315885]])

Que: Make a numpy array of 3x2 containing random integer in the range 1 to 20

In [112]:
# import random
# l = []
# for i in range(20):
#     l.append(random.randint(1,21))
# print(l)
y=np.linspace(1,20,6,dtype = int)
# y=y.astype(int)  
# print(np.linspace(1,20,6,dtype = int))
print(y.reshape(3,2))

[[ 1  4]
 [ 8 12]
 [16 20]]


Que: Reverse the numpy array ?

In [114]:
a = list(map(int, input().split( )))
print(np.array(a)[::-1])

1 2 3 4 5
[5 4 3 2 1]


In [129]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,3))
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [133]:
arr = np.arange(11,5,-1)
print(arr)

[11 10  9  8  7  6]


In [136]:
print(np.empty((10,10)))

[[7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304]
 [7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304 7.74860419e-304 7.74860419e-304
  7.74860419e-304 7.74860419e-304

In [137]:
import math

In [145]:
d = {[1,2]:2}
d

TypeError: unhashable type: 'list'